# Generated by Django 6.0.3 on 2026-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Mon-Fri', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
