# Generated by Django 6.0.3 on 2026-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
